version: "3.9"

x-aws-vpc: ${VPC}
x-aws-cluster: ${CLUSTER}

services:
  proxy-server:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/proxy-server-jd:latest
    environment:
      - USER_SERVICE=${USER_SERVICE}
      - UNDERWRITER_SERVICE=${UNDERWRITER_SERVICE}
      - ACCOUNT_SERVICE=${ACCOUNT_SERVICE}
      - TRANSACTION_SERVICE=${TRANSACTION_SERVICE}
      - BANK_SERVICE=${BANK_SERVICE}
    networks:
      - default
      - public
networks:
  default:
    external: true
    name: ${SG_PRIVATE}
  public:
    external: true
    name: ${SG_PUBLIC}

x-aws-cloudformation:
  Resources:
    ProxyserverService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${SUBNET_ONE}